### ISSUE TITLE
ios版本似乎有些问题

### ISSUE THREAD

**Issue by shangrenxi** [akl7777777/free-chatgpt-client-mobile-pub#1]
ios系统：16.1
版本：1.0.6
签名：开发者自签
问题：在release下载的ipa文件，轻松签选择导入到应用库提示未能找到.app文件。全能签提示，导入的ipa文件有错误，导入失败。

**Comment by akl7777777** [comment]
@shangrenxi 你好,我重新打了个包,你再试试呗; [ChatGPTMobile.ipa](https://github.com/akl7777777/free-chatgpt-client-mobile-pub/releases/download/v1.0.6/ChatGPT_akl.ipa)

**Comment by akl7777777** [comment]
@shangrenxi 已修复...终于打包成功了 ,最新版IOS文件 https://github.com/akl7777777/free-chatgpt-client-mobile-pub/releases/download/v1.1.5/ChatGPTMobile_v1.1.5.ipa

**Comment by akl7777777** [comment]
又更新了 https://github.com/akl7777777/free-chatgpt-client-mobile-pub/releases/download/v1.1.7/ChatGPTMobile_v1.1.7.ipa
