### ISSUE TITLE
ios软件包问题

### ISSUE THREAD

**Issue by mdzz9527** [akl7777777/free-chatgpt-client-mobile-pub#2]
系统:ios16.4, iphone14ProMax
全能签签名安装后,打开后闪退

**Comment by akl7777777** [comment]
@x-otto-x 已修复,重新打了个包,烦请再试试 https://github.com/akl7777777/free-chatgpt-client-mobile-pub/releases/download/v1.1.5/ChatGPTMobile_v1.1.5.ipa

**Comment by akl7777777** [comment]
又更新了1.1.7   https://github.com/akl7777777/free-chatgpt-client-mobile-pub/releases/download/v1.1.7/ChatGPTMobile_v1.1.7.ipa
